<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-JEI8AS0O" ignored="1" name="Test" tests="5" failures="1" timestamp="15 Dec 2019 19:54:53 GMT" time="18.967" errors="0">
  <testcase name="verifyLogin" time="1.029" classname="testcases.HRMTestCases"/>
  <testcase name="validateFirstLevelMenu" time="1.287" classname="testcases.HRMTestCases"/>
  <testcase name="f" time="0.002" classname="testcases.SecondTestClass"/>
  <testcase name="second" time="0.001" classname="testcases.HRMTestCases"/>
  <testcase name="fisrt" time="0.009" classname="testcases.HRMTestCases">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testcases.HRMTestCases.fisrt() didn&amp;apos;t finish within the time-out 2">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testcases.HRMTestCases.fisrt() didn't finish within the time-out 2
at java.lang.Thread.interrupt(Thread.java:919)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 2 stack frames]]>
    </failure>
  </testcase> <!-- fisrt -->
  <testcase name="third" time="0.0" classname="testcases.HRMTestCases">
    <ignored/>
  </testcase> <!-- third -->
</testsuite> <!-- Test -->
